### ISSUE TITLE
Hello ruit and ur pretty cat

### ISSUE THREAD

**Issue by BombHacker** [MJx0/KittyMemory#13]
Could i get contact to your cat or he is gonna send request to me Bomb Hacker#3087.
My youtube https://youtube.com/c/BombHacker1. Yes thats my mods.

**Comment by Rednick16** [comment]
Ruit heres my telegram bro
https://t.me/AltRed16

🤣

**Comment by BombHacker** [comment]
Ok so im gonna dm your cat in telegram

**Comment by BombHacker** [comment]
Ok if u can gimme ur cat telegram, u can email bomba hackier. Email: bombhacker70@gmail.com.

**Comment by BombHacker** [comment]
I am from polarmods btw 🐈

**Comment by busmanl30** [comment]
https://t.me/busmanl30 as well

**Comment by ArcyMods** [comment]
Busman ur late

**Comment by BombHacker** [comment]
Okay then i hope ur going to add me https://t.me/BombHacker123
