### ISSUE TITLE
ios non jailbreak crash

### ISSUE THREAD

**Issue by iAkroma** [MJx0/KittyMemory#17]
hi, help please
why a unity framework path i write in my code with cydia substrate?
i use sideloadly to load a deb file
contact: danielakro#7435

**Comment by MJx0** [comment]
@iAkroma won't work without jailbreak because of codesign

**Comment by iAkroma** [comment]
okay and how work a substrate hook without
<getRealOffset>?

**Comment by MJx0** [comment]
@iAkroma same story. without jailbreak, patching code at run time will break codesign and crash.
