### ISSUE TITLE
Crashes with JIT

### ISSUE THREAD

**Issue by YeetDisDude** [MJx0/KittyMemory#20]
so im trying to use kittymemory on a non jailbroken device with JIT enabled through sideloadly but it stil crashes
and i also made sure the same code works for a jailbroken device
any ideas why it wont work even with jit?

**Comment by globusV1** [comment]
confirm crashing
il use vm_writedata.h 
instead

**Comment by YeetDisDude** [comment]
> confirm crashing
> il use vm_writedata.h
> instead

What do you mean? @globusV1

**Comment by globusV1** [comment]
i didnt use for sideload kittymemory
and using vm_writedata.h

**Comment by YeetDisDude** [comment]
> 
hm, even vm_writedata.h doesn't work for me, it doesnt crash it just doesnt do anything, any ideas?
@globusV1

**Comment by globusV1** [comment]
@YeetDisDude 
works only with JIT enabled

**Comment by YeetDisDude** [comment]
> @YeetDisDude
> works only with JIT enabled

right now i can only edit 4 bytes, do you know how i can edit 8? ive tried changing the parameters and stuff but it still wont work
@globusV1
