### ISSUE TITLE
Runtime patching for Jailed

### ISSUE THREAD

**Issue by Leeksov** [MJx0/KittyMemory#23]
If I can Inject into an application installed from the AppStore, but I don't have JB, will KittyMemory work? The same question is, will KittyMemory work on TrollStore?

**Comment by MJx0** [comment]
I couldn't enable JIT with sideloadly on my iOS 16 device, unfortunately I don't have an older iOS to try.
If you are able to enable JIT on your end then you can try it. I also heard there is another method to make patch works on IG but I haven't been keeping up with the iOS news ):

**Comment by Leeksov** [comment]
Also KittyMemory work with Bootstrap, it support 14.0-17.0 ;)
