### ISSUE TITLE
Error in MemoryPatch::createWithHex()

### ISSUE THREAD

**Issue by slavadynasty** [MJx0/KittyMemory#24]
The address is shifted 1000 ahead of the specified one. For example, I specified libProc + 0x277CFF4, but the data changed to 0x277BFF4. im using last version

`MemoryPatch hashCheck = MemoryPatch::createWithHex(libProc, 0x277CFF4, "C0 07 00 B4 C0 07 00 B4 93 07 00 B4 93 07 00 B4");`

**Comment by MJx0** [comment]
page align is only used for mprotect and target address should not change. Im not able to reproduce this issue, if possible then provide an example code that i can test

**Comment by ShiroAndShuvi** [comment]
Simply take RVA instead of Offset from the dump.cs file
