### ISSUE TITLE
Error in compilation

### ISSUE THREAD

**Issue by Leeksov** [MJx0/KittyMemory#26]
Undefined symbols for architecture arm64:
  "_ks_asm", referenced from:
      __ZN11MemoryPatch13createWithAsmEm11MP_ASM_ARCHRKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEm in MemoryPatch.cpp.cdf2922f.o
  "_ks_close", referenced from:
      __ZN11MemoryPatch13createWithAsmEm11MP_ASM_ARCHRKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEm in MemoryPatch.cpp.cdf2922f.o
  "_ks_errno", referenced from:
      __ZN11MemoryPatch13createWithAsmEm11MP_ASM_ARCHRKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEm in MemoryPatch.cpp.cdf2922f.o
  "_ks_free", referenced from:
      __ZN11MemoryPatch13createWithAsmEm11MP_ASM_ARCHRKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEm in MemoryPatch.cpp.cdf2922f.o
  "_ks_open", referenced from:
      __ZN11MemoryPatch13createWithAsmEm11MP_ASM_ARCHRKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEm in MemoryPatch.cpp.cdf2922f.o
  "_ks_strerror", referenced from:
      __ZN11MemoryPatch13createWi

**Comment by Leeksov** [comment]
i'm add this to makefile and get this: make[3]: *** No rule to make target '/KittyMemory/Deps/Keystone/libs-ios/arm64/libkeystone.a', needed by '/home/leeksov/carxstreet/.theos/obj/arm64/carxstreet.dylib'.  Stop.
make[3]: *** Waiting for unfinished jobs....

**Comment by Leeksov** [comment]
I corrected the previous error by writing this: 
$(TWEAK_NAME)_OBJ_FILES = KittyMemory/Deps/Keystone/libs-ios/$(THEOS_CURRENT_ARCH)/libkeystone.a

But again I got a new one: 
Undefined symbols for architecture arm64e:
   "__ZN11KittyMemory18getAbsoluteAddressEPKcm", referenced from:
       __Z13getRealOffsety in Tweak.xm.7d0af127.o
   "__ZN11MemoryPatch13createWithHexEPKcmRKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE", referenced from:
       -[OffsetSwitch initHackNamed:description:offsets:bytes:] in Menu.mm.7d0af127.o
   "__ZN11MemoryPatch13createWithHexEmNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE", referenced from:
       __Z11patchOffsetyNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE in Tweak.xm.7d0af127.o
   "__ZN11MemoryPatch6ModifyEv", referenced from:
       __Z11patchOffsetyNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE in Tweak.xm.7d0af127.o
       __Z18restoreLastSessionv in Menu.mm.7d0af127.o
       -[Menu switchClicked:] in Menu.mm.7d0af127.o
   "__ZN11MemoryPatch7RestoreEv", referenced from:
       __Z18restoreLastSessionv in Menu.mm.7d0af127.o
       -[Menu switchClicked:] in Menu.mm.7d0af127.o
   "__ZN11MemoryPatchD1Ev", referenced from:
       __Z11patchOffsetyNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE in Tweak.xm.7d0af127.o
       -[OffsetSwitch initHackNamed:description:offsets:bytes:] in Menu.mm.7d0af127.o
       __ZNSt3__113__vector_baseI11MemoryPatchNS_9allocatorIS1_EEED2Ev in Menu.mm.7d0af127.o
       __ZNSt3__114__split_bufferI11MemoryPatchRNS_9allocatorIS1_EEED2Ev in Menu.mm.7d0af127.o
   "__ZNK11MemoryPatch7isValidEv", referenced from:
       __Z11patchOffsetyNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE in Tweak.xm.7d0af127.o
       -[OffsetSwitch initHackNamed:description:offsets:bytes:] in Menu.mm.7d0af127.o
ld: symbol(s) not found for architecture arm64e

**Comment by HaidarPhantom** [comment]
> I corrected the previous error by writing this: (TWEAKNAME)OBJFILES=KittyMemory/Deps/Keystone/libs−ios/(THEOS_CURRENT_ARCH)/libkeystone.a
> 
> But again I got a new one: Undefined symbols for architecture arm64e: "__ZN11KittyMemory18getAbsoluteAddressEPKcm", referenced from: __Z13getRealOffsety in Tweak.xm.7d0af127.o "__ZN11MemoryPatch13createWithHexEPKcmRKNSt3__112basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEE", referenced from: -[OffsetSwitch initHackNamed:description:offsets:bytes:] in Menu.mm.7d0af127.o "__ZN11MemoryPatch13createWithHexEmNSt3__112basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE", referenced from: __Z11patchOffsetyNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE in Tweak.xm.7d0af127.o "__ZN11MemoryPatch6ModifyEv", referenced from: __Z11patchOffsetyNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE in Tweak.xm.7d0af127.o __Z18restoreLastSessionv in Menu.mm.7d0af127.o -[Menu switchClicked:] in Menu.mm.7d0af127.o "__ZN11MemoryPatch7RestoreEv", referenced from: __Z18restoreLastSessionv in Menu.mm.7d0af127.o -[Menu switchClicked:] in Menu.mm.7d0af127.o "__ZN11MemoryPatchD1Ev", referenced from: __Z11patchOffsetyNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE in Tweak.xm.7d0af127.o -[OffsetSwitch initHackNamed:description:offsets:bytes:] in Menu.mm.7d0af127.o __ZNSt3__113__vector_baseI11MemoryPatchNS_9allocatorIS1_EEED2Ev in Menu.mm.7d0af127.o __ZNSt3__114__split_bufferI11MemoryPatchRNS_9allocatorIS1_EEED2Ev in Menu.mm.7d0af127.o "__ZNK11MemoryPatch7isValidEv", referenced from: __Z11patchOffsetyNSt3__112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEE in Tweak.xm.7d0af127.o -[OffsetSwitch initHackNamed:description:offsets:bytes:] in Menu.mm.7d0af127.o ld: symbol(s) not found for architecture arm64e

did you fix this ? i have the same problem

**Comment by MJx0** [comment]
undefined symbols means you did not add the source files to your $(TWEAK_NAME)_FILES
