### ISSUE TITLE
Crash when searching outside the library range with KittyScanner

### ISSUE THREAD

**Issue by knms360** [MJx0/KittyMemory#28]
In the sample, the search range is specified using ELF.baseSegment().startAddress and ELF.baseSegment().endAddress. However, if I use an arbitrary search range, it crashes. It is most likely that the program is crashing because it is reading an unreadable range.
There are no errors when compiling. can get the error with Logcat
Error:
Fatal signal 11 (SIGSEGV), code 2, fault addr 0xf15b6000 in tid 3825 (android.support)

**Comment by knms360** [comment]
My Code
`            KittyScanner::ElfScanner g_il2cppELF;
            g_il2cppELF = KittyScanner::ElfScanner::createWithPath("libMyLibName.so");
            uintptr_t search_start = g_il2cppELF.baseSegment().startAddress;
            uintptr_t search_end = g_il2cppELF.baseSegment().endAddress + 0xFFFF;
            std::vector<uintptr_t> found_at_list;
            found_at_list = KittyScanner::findHexAll(search_start, search_end,  "01 01 01 00 01 00 00 00 01 00 00 00 01 00 00 00 01 01 00 00", "xxxxxxxxxxxxxxxxxxxx");`

**Comment by MJx0** [comment]
```uintptr_t search_end = g_il2cppELF.baseSegment().endAddress + 0xFFFF; ```
why the + 0xFFFF ?

**Comment by knms360** [comment]
> `uintptr_t search_end = g_il2cppELF.baseSegment().endAddress + 0xFFFF; ` why the + 0xFFFF ?

This is to make it clear that it is outside the range.
uintptr_t search_end = 0xFFFF; didn't work either. I get the same error.

**Comment by MJx0** [comment]
there is no memory permissions checks inside scanner functions. you have to check and provide valid readable memory range by yourself. if you want to scan a full library then use segments array instead of only the base segment, them check which segment is readable

**Comment by knms360** [comment]
Is it possible to read the segment from 0x00 to 0xFFFFFFFF and check if it is readable?

**Comment by MJx0** [comment]
Why would you use hardcoded memory range?
you can call getAllMaps() function to get all process memory maps then filter them

**Comment by knms360** [comment]
Because there is no library that can be used to look up byte arrays.
(It's difficult to explain in English, so please refer to the image)
![gamegu1](https://github.com/MJx0/KittyMemory/assets/123563501/181345e5-b6b1-4f55-8ddb-da2596d5e40b)
![gamegu2](https://github.com/MJx0/KittyMemory/assets/123563501/4ff1dab2-6ac2-492f-8d89-804ce45e87f6)

**Comment by MJx0** [comment]
use termux and print process maps
```
cat /proc/<pid>/maps
```
it could be malloc memory or bss.

**Comment by knms360** [comment]
Ah, um... it seems very difficult, but I'll try it.

**Comment by knms360** [comment]
That's right, it was in the range of anon:libc_malloc

**Comment by MJx0** [comment]
You can get malloc memory path with this, but on older android versions it might be empty
```
std::string mallocPathname()
{
    void *n = malloc(sizeof(void*));

    if (auto fMaps = fopen("/proc/self/maps", "r"))
    {
        char cLine[512] = { 0 };
        while (fgets(cLine, sizeof(cLine), fMaps) != nullptr)
        {
            unsigned long long start = 0, end = 0;
            char pathanme[0xff] = { 0 };
            sscanf(cLine, "%llx-%llx %*s %*s %*s %*s %s", &start, &end, pathanme);
            if (uintptr_t(n) >= start && uintptr_t(n) < end) return pathanme;
        }
        fclose(fMaps);
    }

    free(n);

    return "";
}
```
You can scan like this after
```
auto mallocPath = mallocPathname();
if (!mallocPath.empty())
{
  auto maps = KittyMemory::getMapsEqual(mallocPath);
  for (const auto &it : maps)
  {
     // filter out 
     if (it.offset != 0 && it.perms.compare("rw-p")) continue;

    uintptr_t found_at = KittyScanner::findIdaPatternFirst(it.startAddress, it.endAddress, "33 ? 55 66 ? 77 88 ? 99");
    KITTY_LOGI("found IDA pattern at: %p", (void *)found_at);
  }
}
```

**Comment by knms360** [comment]
Thanks!!
I will give it a try. Thank you so much.

**Comment by knms360** [comment]
Hey, An error occurs in it.perms.compare
No member named 'perms' in 'KittyMemory::ProcMap'

**Comment by knms360** [comment]
But... I fixed the code and it worked. Was this ok?
if (it.offset != 0) continue;
![oauhfiae](https://github.com/MJx0/KittyMemory/assets/123563501/d0a10604-a21d-4a4c-a83a-496f203d9e72)

**Comment by knms360** [comment]
Hey

**Comment by MJx0** [comment]
offset == 0 and perms are just checks to filter out unnecessary maps to speed up the scan but you don't really need it

**Comment by knms360** [comment]
OK, Thanks! I'll try later. maybe this issue will be over.

**Comment by knms360** [comment]
It has been confirmed that it does not work on some devices. Android versions are 7 and 11.
