### ISSUE TITLE
Help !!!

### ISSUE THREAD

**Issue by Mahmoud-GMG** [MJx0/KittyMemory#6]
Bro, I can get the offset but how to get this values ((mov r0, #1 bx  lr))
I need it to get hex codes, please help !!!!!!! ♡♡♡♡♡

**Comment by MrPictYT-art** [comment]
Put It Here https://armconverter.com/

**Comment by Mafiaboy2020** [comment]
> Bro, I can get the offset but how to get this values ((mov r0, #1 bx lr))
> I need it to get hex codes, please help !!!!!!! ♡♡♡♡♡

Hello my friend, you can open the HxD program and search for the option to go to compensation. Set your address and choose 4 bytes for armv7 processor and 8 bytes for v8 arm processor
For Example : 
[7F 7E 00 00] FF FA 00 00 00

**Comment by Mahmoud-GMG** [comment]
> Put It Here https://armconverter.com/

Bro I mean : how to get the values not convert it

**Comment by PMTLEGEND** [comment]
Bro put the converted assembly code in reverse hex to decimal converter
