### ISSUE TITLE
another app pid

### ISSUE THREAD

**Issue by NettixCode** [MJx0/KittyMemory#9]
hello .. in kittymemory.cpp has a code FILE *fp = fopen("/proc/self/maps", "rt");
it to get self app pid right ?
if i want to find another app pid how to code it ? can you help ?

example i want to know what gmail pid .. how i must code it ?
FILE *fp = fopen("/proc/(how to get gmail pid here)/maps", "rt");

**Comment by Rednick16** [comment]
KittyMemory works internally only, so it won’t work externally you will need to use writeProccess memory to attach to external proccess
